version: "3.9"

services:
  x-monitor:
    image: xmonitor-pro:v10.4
    container_name: x-monitor
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    shm_size: 1g
    restart: unless-stopped
